name: TNEB Outage Crawler

on:
  schedule:
    # Run daily at 11:30 UTC (17:00 IST)
    - cron: '30 11 * * *'
  workflow_dispatch:

jobs:
  crawl-outages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr tesseract-ocr-eng
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run TNEB Crawler
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        APPCAT_CODE: ${{ secrets.APPCAT_CODE }}
      run: |
        python power-alert.py --run-once
    - name: Upload logs (if any)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: crawler-logs
        path: |
          *.log
          logs/
        retention-days: 7